import type { HintCategory } from '../ledger/snapshot.js';

export interface Remedy {
  code: string;
  category: HintCategory;
  severity: 'info' | 'warn' | 'error';
  /** What the hint means. */
  meaning: string;
  /** What to change, imperative and concrete. */
  fix: string;
  /** The threeforge or three.js API to reach for. */
  api: string;
  /** Where to read more in the repository. */
  docs: string;
}

const remedy = (code: string, category: HintCategory, severity: Remedy['severity'], meaning: string, fix: string, api: string, docs = 'README.md'): [string, Remedy] => [code, { code, category, severity, meaning, fix, api, docs }];

/** One entry per hint code `hintsFor` can emit (a unit test enforces the match). */
export const REMEDIES: Record<string, Remedy> = Object.fromEntries([
  remedy('over-budget-submissions', 'drawCalls', 'error', 'The frame issues more scene submissions (render items) than the device tier can afford.', 'Tag static meshes with tag.static() and run world.compile() so they batch; lower instanceThreshold so repeated geometry instances; use fewer shadow-casting lights (each is one more pass over the casters).', 'tag.static(), new World(scene, { instanceThreshold }).compile()', 'README.md#what-the-numbers-mean'),
  remedy('over-budget-triangles', 'drawCalls', 'warn', 'More triangles are rasterised per frame than the tier budget.', 'Generate LODs with prepareLods() and pass lod distances to World so distant batches draw simplified geometry; simplify heavy assets at build time; make sure per-instance culling is on (culling: "bvh").', 'prepareLods(scene, { ratios }), new World(scene, { lod: { distances } })'),
  remedy('untagged', 'drawCalls', 'warn', 'Meshes without a forge tag are left alone by the compiler and drawn one by one.', 'Call tag.static(mesh) on everything that never moves and tag.dynamic(mesh) on the rest, or construct World with policy: "auto" to batch untagged plain meshes.', 'tag.static(), tag.dynamic(), new World(scene, { policy: "auto" })'),
  remedy('unique-materials', 'drawCalls', 'info', 'Many meshes carry a material instance used by nothing else, so nothing can share a batch or a program.', 'Create one material per surface type and share it, or pass every material through registry.register() and use the canonical it returns; identical materials then merge.', 'registry.register(material), registry.stats().byProgram'),
  remedy('static-unbatched', 'drawCalls', 'info', 'Static meshes still draw one submission each although another object of the main pass draws the same material: nothing merged them into a batch. Which submissions carry this reason is decided by the frame\'s main-pass users of that material, so a submission in a `scene:` or `nested:` pass carries it too when main-pass objects share its material.', 'Compile the scene with World so statics that share a material batch. If World already compiled them, each was left alone in its group: World groups statics by material variant, geometry attribute set, castShadow and receiveShadow (and chunk cell with chunkSize), and a mesh left over after instancing takes its group\'s repeated geometry stays alone too. Align those across the meshes of one material, or accept the draws. The other draw of that material may itself be one nothing can batch with (skinned, dynamic, or already batched), in which case there is nothing to merge.', 'tag.static(), new World(scene).compile(), CompileReport.skipped (rule "singleton")'),
  remedy('unsupported-material', 'drawCalls', 'error', 'ShaderMaterial and RawShaderMaterial do not render on WebGPURenderer at all.', 'Rewrite the effect with three shading language (TSL) on a NodeMaterial, or use a built-in material with node overrides.', 'MeshStandardNodeMaterial, three/tsl'),
  remedy('programs', 'drawCalls', 'warn', 'Many distinct shader programs: every variant costs a compile and every switch costs GPU state changes.', 'Reduce material variants: same map slots, same flags (side, transparent, alphaTest, vertexColors) across materials of a kind; colour differences are free, flag differences are not.', 'registry.stats().byProgram, registry.describe(material)'),
  remedy('transparent-overdraw', 'overdraw', 'warn', 'Transparent fragments per pixel exceed the tier budget: fill rate, not draw calls, is the cost.', 'Use alphaTest cutouts instead of blending for foliage and fences, cap particles with ParticleBudget, batch sprites (World\'s default sprites: "batch"), shrink billboard sizes, and scale the drawing buffer with ResolutionScaler on low tiers.', 'material.alphaTest, ParticleBudget, ResolutionScaler, ledger.measureOverdraw()'),
  remedy('particles-over-budget', 'overdraw', 'warn', 'More particles (points vertices, sprites and sprite-batch instances) are drawn per frame than the tier budget; each is a transparent quad that costs fill rate.', 'Apply new ParticleBudget({ tier }).apply(scene) so every system\'s drawRange scales down to the budget, spawn fewer particles on phones, and shrink point sizes (pointSizeScale).', 'new ParticleBudget({ tier, particles, pointSizeScale }).apply(scene), geometry.setDrawRange()'),
  remedy('sprites-unbatched', 'overdraw', 'info', 'Many Sprite objects are drawn one submission each although they share a material.', 'Keep World\'s sprites: "batch" (the default) so sprites sharing a material become one instanced billboard draw synced every frame; give each effect one SpriteMaterial instead of one per sprite.', 'new World(scene, { sprites: "batch", spriteThreshold })'),
  remedy('skinned-vertices', 'skinning', 'warn', 'Skinned vertices per frame exceed the tier budget; each is skinned by the GPU every frame.', 'Merge gear onto one skeleton with assembleCharacter(), use lower-poly rigs for background characters, and bake crowds: bakeAnimationTexture() once per prototype, then AnimatedInstances draws every character of that prototype as one instanced draw per part.', 'assembleCharacter({ skeleton, wardrobe, equipped }), bakeAnimationTexture(prototype, clips), new AnimatedInstances({ animation, count })'),
  remedy('bones-over-budget', 'skinning', 'warn', 'Every skinned mesh updates its whole skeleton on the CPU every frame; this many bones cost JavaScript time before the GPU sees them.', 'Bake crowds to animation textures (AnimatedInstances updates no bones), share skeletons between parts with assembleCharacter(), and rig background characters with fewer bones.', 'bakeAnimationTexture(), AnimatedInstances, assembleCharacter()'),
  remedy('skinned-crowd', 'skinning', 'info', 'Many skinned draws on screen: each one is a draw call plus a skeleton update, and batching cannot touch skinned meshes.', 'Bake the prototype\'s clips once with bakeAnimationTexture() and build the crowd with AnimatedInstances: one instanced draw per part, each instance with its own clip, offset and speed.', 'bakeAnimationTexture(prototype, clips, { fps }), new AnimatedInstances({ animation, count }).setClipAt(i, clip)'),
  remedy('point-light-shadow', 'lighting', 'warn', 'A shadow-casting point light renders six shadow faces every frame.', 'Replace it with a spot light (one face), freeze its shadow map with ShadowBudget.freeze(light) and refresh it only when casters move, or let new ShadowBudget({ tier }).apply(scene) switch point shadows off on phones.', 'SpotLight, ShadowBudget.freeze(light), new ShadowBudget({ tier }).apply(scene)'),
  remedy('shadow-texels', 'lighting', 'warn', 'Shadow-map texels rendered per frame exceed the tier budget.', 'Apply new ShadowBudget({ tier }).apply(scene) so the largest maps halve until the tier budget holds (point shadows off on phones, off: [tiers] for none), freeze static shadow maps with ShadowBudget.freeze(light), and let DayNight re-render the sun shadow only when the sun moved.', 'new ShadowBudget({ tier, off }).apply(scene), ShadowBudget.freeze(light), new DayNight(scene, { shadow: { everyDegrees } })'),
  remedy('transmission', 'overdraw', 'info', 'A transmissive material renders in two passes and copies the frame buffer for refraction.', 'Keep transmission for a few hero objects, set forceSinglePass when the object is not double sided, and fake distant glass with opacity.', 'material.transmission, material.forceSinglePass'),
  remedy('transparent-batch-order', 'overdraw', 'info', 'A threeforge transparent batch shares the main pass with other transparent submissions; three sorts a BatchedMesh back-to-front by its own bounding-sphere centre, not per instance, so it composites in creation order relative to those other transparent draws instead of true per-object depth.', "Construct World with transparent: 'keep' to leave transparent statics as individual meshes when exact draw order against other transparent objects matters (e.g. overlapping glass close to the camera); opaque statics still batch normally.", "new World(scene, { transparent: 'keep' })"),
  remedy('batch-local-space', 'drawCalls', 'warn', "A threeforge batch, instanced group or baked mesh draws with a material threeforge cannot rule out reading mesh-local space: a node in any slot, material code the hint cannot read (a class that is not one of three's own, or an own function), alphaHash, or an object-space normal map. A node graph and a subclass are named because they cannot be inspected, not because they were found to read it; alphaHash and an object-space normal map do read it. three r186 gives such a draw the scene's space instead of each mesh's own. Batching and instancing multiply positionLocal by the instance matrix (Batch.js, Instance.js) and a baked mesh's positions are written in scene space; positionLocal is a varying, so a node that reads it (a gradient in colorNode, an offset in positionNode) and alphaHash, which hashes it to choose the pixels it discards, may draw differently than the individual meshes did. An object-space normal map's normals go through the draw's model normal matrix (NormalMapNode.js), the batch's rather than each mesh's, so a rotated mesh is lit as if unrotated. The hint can see into neither a node graph nor code: it names every material with a node in a slot, a subclass or an own function, including those that never read positionLocal. It is a warn rather than an info because the change is to shading on default settings, not to a timing or a count.", "Where the change shows, tag the meshes that must shade in their own local space with tag.dynamic() so World leaves them individual draws (under the default dynamics: 'separate'; 'batch-sync' batches dynamics too). For object-space normal maps, a tangent-space map (normalMapType: TangentSpaceNormalMap) batches unchanged. Leave the rest batched where the difference does not matter: batching stays the default.", "tag.dynamic(mesh), new World(scene, { dynamics: 'separate' }), material.normalMapType", 'docs/threeforge.md'),
  remedy('texture-bytes', 'memory', 'warn', 'Estimated texture memory exceeds the tier budget.', 'Compress textures to KTX2 (toktx or gltf-transform), cap sizes per tier, share atlases, and drop mipmaps only for UI textures.', 'createLoader() (KTX2Loader wired), threeforge optimize --textures webp, gltf-transform'),
  remedy('geometry-bytes', 'memory', 'warn', 'Estimated geometry memory exceeds the tier budget.', 'Compress with threeforge optimize --compress meshopt (or Draco), generate LODs (prepareLods), compile with chunkSize and stream chunks with a Streamer.', 'threeforge optimize, prepareLods(), World({ chunkSize }), Streamer'),
  remedy('unreferenced-resources', 'memory', 'warn', 'The renderer still holds geometries or textures that nothing in the scene references: they were removed without dispose().', 'Track loaded subtrees with a ResourceTracker and release() them when removed; dispose textures and geometries you replace; let a Streamer unload chunks.', 'ResourceTracker, unreferencedResources(), Streamer'),
  remedy('js-objects', 'js', 'warn', 'three walks every object in the scene twice per frame (world matrices, then the render list); this many costs JavaScript time on every frame.', 'Compile with World so statics batch, pass originals: "detach" so hidden originals leave the graph, flatten empty groups, and keep helper objects out of the rendered scene.', 'new World(scene, { originals: "detach" })'),
  remedy('detach-originals', 'js', 'info', 'Batched originals stay in the graph on a hidden layer by default, and three still visits each of them every frame.', 'Construct World with originals: "detach": the originals leave the graph (and both per-frame walks) and decompile() puts them back at their old index.', 'new World(scene, { originals: "detach" })'),
  remedy('static-auto-update', 'js', 'info', 'Static-tagged objects still recompute their world matrices every frame.', 'After placing a static object set matrixAutoUpdate = false (and matrixWorldAutoUpdate = false on whole static subtrees); update matrices manually when something does move.', 'object.matrixAutoUpdate, object.updateMatrix()'),
]);

export function explain(code: string): Remedy | null {
  return REMEDIES[code] ?? null;
}
