// Renders docs/bench.md from the committed baselines and refreshes the README section between the bench markers.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { baselinePath, table } from './bench-gate.mjs';

const sections = [];
for (const backend of ['webgl2', 'webgpu']) {
  if (!existsSync(baselinePath(backend))) continue;
  const b = JSON.parse(readFileSync(baselinePath(backend), 'utf8'));
  sections.push(`### ${backend}\n\n${b.env?.gpu ?? 'unknown GPU'} · tier ${b.env?.tier ?? '?'} · three ${b.env?.three ?? '?'}\n\n${table(b)}`);
}
const body = sections.length ? sections.join('\n\n') : '_No baselines yet: run `pnpm bench` then `pnpm bench:baseline`._';
const doc = `# Benchmark baselines\n\nGenerated by \`pnpm bench:baseline\` from \`bench/baselines/*.json\`. Each row is one scene: naive assembly → optimized through threeforge. Timing columns are medians of 60 frames on the machine that produced the baseline; they are gated only with \`FORGE_GPU=native\`.\n\n${body}\n`;
writeFileSync('docs/bench.md', doc);
const readmePath = 'README.md';
if (existsSync(readmePath)) {
  const readme = readFileSync(readmePath, 'utf8');
  const start = '<!-- bench:start -->';
  const end = '<!-- bench:end -->';
  if (readme.includes(start) && readme.includes(end)) {
    const before = readme.slice(0, readme.indexOf(start) + start.length);
    const after = readme.slice(readme.indexOf(end));
    writeFileSync(readmePath, `${before}\n${body}\n${after}`);
  }
}
console.log('docs/bench.md written');
