// node scripts/draco-fixture.mjs: rebuilds test/fixtures/draco from nothing. One lit torus, 32 x 16 segments, written
// plain and with KHR_draco_mesh_compression, so a test can load the same mesh with and without the Draco decoder.
// Needs the optional peer `draco3dgltf` for encoding; the tests that load the fixtures need only the files.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { Document, NodeIO } from '@gltf-transform/core';
import { KHRDracoMeshCompression } from '@gltf-transform/extensions';
import { draco } from '@gltf-transform/functions';
import draco3d from 'draco3dgltf';

const OUT = 'test/fixtures/draco';
const [ACROSS, DOWN] = [32, 16];

/** A torus: closed like a sphere, but with no poles, so no triangle collapses and Draco keeps every face. */
function torus() {
  const positions = [];
  const normals = [];
  const indices = [];
  for (let row = 0; row <= DOWN; row++)
    for (let column = 0; column <= ACROSS; column++) {
      const [tube, around] = [(row / DOWN) * 2 * Math.PI, (column / ACROSS) * 2 * Math.PI];
      const normal = [Math.cos(tube) * Math.cos(around), Math.sin(tube), Math.cos(tube) * Math.sin(around)];
      positions.push(
        0.35 * Math.cos(around) + 0.15 * normal[0],
        0.15 * normal[1],
        0.35 * Math.sin(around) + 0.15 * normal[2],
      );
      normals.push(...normal);
    }
  for (let row = 0; row < DOWN; row++)
    for (let column = 0; column < ACROSS; column++) {
      const a = row * (ACROSS + 1) + column;
      const b = a + ACROSS + 1;
      indices.push(a, a + 1, b, b, a + 1, b + 1);
    }
  return {
    positions: new Float32Array(positions),
    normals: new Float32Array(normals),
    indices: new Uint16Array(indices),
  };
}

function document() {
  const doc = new Document();
  const buffer = doc.createBuffer();
  const { positions, normals, indices } = torus();
  const position = doc.createAccessor().setType('VEC3').setArray(positions).setBuffer(buffer);
  const normal = doc.createAccessor().setType('VEC3').setArray(normals).setBuffer(buffer);
  const material = doc.createMaterial('clay').setBaseColorFactor([0.8, 0.45, 0.3, 1]).setRoughnessFactor(0.7);
  const primitive = doc
    .createPrimitive()
    .setAttribute('POSITION', position)
    .setAttribute('NORMAL', normal)
    .setIndices(doc.createAccessor().setType('SCALAR').setArray(indices).setBuffer(buffer))
    .setMaterial(material);
  doc.createScene().addChild(doc.createNode('ring').setMesh(doc.createMesh('ring').addPrimitive(primitive)));
  return doc;
}

mkdirSync(OUT, { recursive: true });
const io = new NodeIO()
  .registerExtensions([KHRDracoMeshCompression])
  .registerDependencies({ 'draco3d.encoder': await draco3d.createEncoderModule() });
writeFileSync(join(OUT, 'ring-plain.glb'), await io.writeBinary(document()));
const compressed = document();
await compressed.transform(draco());
writeFileSync(join(OUT, 'ring-draco.glb'), await io.writeBinary(compressed));
writeFileSync(
  join(OUT, 'README.md'),
  '# Draco fixtures\n\nGenerated by `node scripts/draco-fixture.mjs`; do not edit by hand. `ring-plain.glb` and `ring-draco.glb` are the same\n' +
    `${ACROSS} x ${DOWN} torus (${ACROSS * DOWN * 2} triangles), the second with \`KHR_draco_mesh_compression\` required.\n`,
);
